// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwbgwwctajsmigpwpszo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3Ymd3d2N0YWpzbWlncHdwc3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzg4MTEsImV4cCI6MjA2NTkxNDgxMX0.lA0-FFOaq7fT1DdBn8iwTdt5Fhs-Zam6JacDY-EgCyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);